import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
const inter = Inter({ subsets: ["latin"] });
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn('h-full font-sans relative antialiased',inter.className)}>
        <main className="min-h-screen relative flex flex-col" >
          <div className="flex-grow">
<Navbar/>
        {children}
          </div>
        </main>
        </body>
    </html>
  );
}
